# Solution for the Titanic challenge using the Naïve-Bayes algorithm

**Libraries**

In [1]:
import pandas as pd
import numpy as np


**Data preprocessing**

In [2]:
titanic_train = pd.read_csv('/content/train.csv')
titanic_train


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
titanic_train.describe()


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [4]:
titanic_train.isnull().sum() # detecting null values


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# removing null values and unecessary columns
titanic_train = titanic_train.dropna(subset=['Age'])
titanic_train = titanic_train.dropna(subset=['Embarked'])
titanic_train = titanic_train.drop(['Name', 'Cabin', 'Ticket' ], axis=1)


In [6]:
titanic_train


PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
885        Q  
886        S  
887        S  
889        C  
890        Q  

[712 rows x 9 columns]

In [7]:
titanic_train.isnull().sum()


PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

**Creating and treating the variables**

In [8]:
# independent variables
columns = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
x_titanic_train = titanic_train[columns].values
x_titanic_train


array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ...,
       [1, 'female', 19.0, ..., 0, 30.0, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [9]:
# dependent variable
y_titanic_train = titanic_train['Survived'].values


In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


In [11]:
# transforming nominal independent variables into numeric ones
one_hot_encoder = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0, 1, 6])], remainder='passthrough')
one_hot_encoder


ColumnTransformer(remainder='passthrough',
                  transformers=[('OneHot', OneHotEncoder(), [0, 1, 6])])

In [12]:
x_titanic_train_transformed = one_hot_encoder.fit_transform(x_titanic_train)


In [13]:
x_titanic_train_array = np.array(x_titanic_train_transformed)
x_titanic_train_array[0]


array([0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 22.0, 1, 0, 7.25],
      dtype=object)

**Standardization of the values**

In [14]:
from sklearn.preprocessing import StandardScaler


In [15]:
scaler_titanic = StandardScaler()
x_titanic_train_standard = scaler_titanic.fit_transform(x_titanic_train_array)


In [16]:
x_titanic_train_standard


array([[-0.59032605, -0.56653751,  1.00281295, ...,  0.52251079,
        -0.50678737, -0.51637992],
       [ 1.69397911, -0.56653751, -0.99719495, ...,  0.52251079,
        -0.50678737,  0.69404605],
       [-0.59032605, -0.56653751,  1.00281295, ..., -0.55271372,
        -0.50678737, -0.50362035],
       ...,
       [ 1.69397911, -0.56653751, -0.99719495, ..., -0.55271372,
        -0.50678737, -0.08633507],
       [ 1.69397911, -0.56653751, -0.99719495, ..., -0.55271372,
        -0.50678737, -0.08633507],
       [-0.59032605, -0.56653751,  1.00281295, ..., -0.55271372,
        -0.50678737, -0.50692839]])

**Aplying the Naïve-Bayes algorithm in the train data**

In [17]:
from sklearn.naive_bayes import GaussianNB


In [18]:
# training the model
naive_titanic = GaussianNB()
naive_titanic.fit(x_titanic_train_standard, y_titanic_train)


GaussianNB()

In [19]:
# pclass, class, class, sex, sex, embarked, embarked, embarked, age, sibsp, parch, fare
prediction = naive_titanic.predict(x_titanic_train_standard)
prediction


array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,

**Measuring the accuracy of the model**

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [21]:
accuracy_score(y_titanic_train, prediction)


0.776685393258427

In [22]:
confusion_matrix(y_titanic_train, prediction)


array([[344,  80],
       [ 79, 209]])

In [23]:
print(classification_report(y_titanic_train, prediction))


              precision    recall  f1-score   support

           0       0.81      0.81      0.81       424
           1       0.72      0.73      0.72       288

    accuracy                           0.78       712
   macro avg       0.77      0.77      0.77       712
weighted avg       0.78      0.78      0.78       712



**Applying the model to test database**

In [35]:
titanic_test = pd.read_csv('/content/test.csv')


In [36]:
titanic_test


PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [37]:
titanic_test.isnull().sum()


PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [38]:
# Storing the id column
PassengerId = titanic_test['PassengerId'].values


In [39]:
# preparing the data
titanic_test = titanic_test.drop(['PassengerId','Name', 'Ticket','Cabin'], axis=1)
mean_age = titanic_test['Age'].mean()
titanic_test['Age'] = titanic_test['Age'].fillna(mean_age)
mean_fare = titanic_test['Fare'].mean()
titanic_test['Fare'] = titanic_test['Fare'].fillna(mean_fare)


In [40]:
titanic_test.isnull().sum()


Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [41]:
test_array = titanic_test[:].values
test_array[0]


array([3, 'male', 34.5, 0, 0, 7.8292, 'Q'], dtype=object)

In [42]:
one_hot_encoder_test = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0, 1, 6])], remainder='passthrough')
titanic_test_transformed = one_hot_encoder.fit_transform(test_array)
titanic_test_transformed


array([[0.0, 0.0, 1.0, ..., 0, 0, 7.8292],
       [0.0, 0.0, 1.0, ..., 1, 0, 7.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 9.6875],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 0, 7.25],
       [0.0, 0.0, 1.0, ..., 0, 0, 8.05],
       [0.0, 0.0, 1.0, ..., 1, 1, 22.3583]], dtype=object)

In [43]:
x_titanic_test_standard = scaler_titanic.fit_transform(titanic_test_transformed)


**Generating the final results**

In [44]:
prediction_test = naive_titanic.predict(x_titanic_test_standard)
prediction_test


array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [45]:
titanic_result = {'PassengerId': PassengerId, 'Survived': prediction_test}
titanic_dataframe = pd.DataFrame(titanic_result )
titanic_dataframe


PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [46]:
titanic_submission = titanic_dataframe.to_csv('titanic_submission.csv', index=False)


## Decision Tree

In [49]:
from sklearn.tree import DecisionTreeClassifier


**Applying the algorithm in the train database**

In [47]:
x_titanic_train_array[0]


array([0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 22.0, 1, 0, 7.25],
      dtype=object)

In [51]:
# training the algorithm
tree_titanic = DecisionTreeClassifier(criterion='entropy')
tree_titanic.fit(x_titanic_train_array, y_titanic_train)


DecisionTreeClassifier(criterion='entropy')

In [52]:
# classifying the importance of the variables
tree_titanic.feature_importances_


array([0.03094769, 0.00112395, 0.09785993, 0.22697588, 0.        ,
       0.0053744 , 0.        , 0.01652242, 0.30594942, 0.05404166,
       0.02643507, 0.23476957])

In [57]:
prediction_train_tree = tree_titanic.predict(x_titanic_train_array)
accuracy_score(y_titanic_train, prediction_train_tree)


0.9859550561797753

**Applying the algorithm in the test database**

In [59]:
prediction_result_tree = tree_titanic.predict(titanic_test_transformed)


In [60]:
titanic_tree_result = {'PassengerId': PassengerId, 'Survived': prediction_result_tree}
titanic_tree_dataframe = pd.DataFrame(titanic_result )
titanic_tree_dataframe


PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [62]:
titanic_tree_submission = titanic_dataframe.to_csv('titanic_tree_submission.csv', index=False)
